/* @flow */

const STOCK_LOOKUP_BEGIN: string = 'STOCK_LOOKUP_BEGIN';
const STOCK_LOOKUP_SUCCESS: string = 'STOCK_LOOKUP_SUCCESS';
const STOCK_LOOKUP_FAILURE: string = 'STOCK_LOOKUP_FAILURE';

// Stock updating from remote location.
const STOCK_REMOTE_UPDATE_BEGIN: string = 'STOCK_REMOTE_UPDATE_BEGIN';
const STOCK_REMOTE_UPDATE_SUCCESS: string = 'STOCK_REMOTE_UPDATE_SUCCESS';
const STOCK_REMOTE_UPDATE_FAILURE: string = 'STOCK_REMOTE_UPDATE_FAILURE';

// Stock batch load from local datastore.
const STOCK_BATCH_LOAD_BEGIN: string = 'STOCK_BATCH_LOAD_BEGIN';
const STOCK_BATCH_LOAD_SUCCESS: string = 'STOCK_BATCH_LOAD_SUCCESS';
const STOCK_BATCH_LOAD_FAILURE: string = 'STOCK_BATCH_LOAD_FAILURE';

// Stock purchase crud.
const STOCK_PURCHASE_CREATE: string = 'STOCK_PURCHASE_CREATE';
const STOCK_PURCHASE_UPDATE: string = 'STOCK_PURCHASE_UPDATE';
const STOCK_PURCHASE_DELETE: string = 'STOCK_PURCHASE_DELETE';

export {
  STOCK_BATCH_LOAD_BEGIN,
  STOCK_BATCH_LOAD_SUCCESS,
  STOCK_BATCH_LOAD_FAILURE,
  STOCK_LOOKUP_BEGIN,
  STOCK_LOOKUP_FAILURE,
  STOCK_LOOKUP_SUCCESS,
  STOCK_PURCHASE_CREATE,
  STOCK_PURCHASE_DELETE,
  STOCK_PURCHASE_UPDATE,
  STOCK_REMOTE_UPDATE_BEGIN,
  STOCK_REMOTE_UPDATE_FAILURE,
  STOCK_REMOTE_UPDATE_SUCCESS
}
